### ISSUE TITLE
`embedded_hal` errors shouldn't be ignored

### ISSUE THREAD

**Issue by ripytide** [rust-embedded-community/tb6612fng-rs#34]
While I was working on #26 and similar pr's I found it strange that various `embedded_hal` errors are just ignored rather than being returned to the caller which seems like the idiomatic thing to do since this is a library.
Example:
https://github.com/rursprung/tb6612fng-rs/blob/82c7c815a49a9e40a0853d095dd8371e6267ed69/src/lib.rs#L237-L238

At first I thought those errors would be encapsulated in `DriveError` but it seems actually that is only for speed errors so maybe it should be renamed `SpeedError`.

**Comment by rursprung** [comment]
you're right, i should've probably propagated this upwards! i think this was just a lazy (late-night?) attempt at quickly porting from e-h 0.2 (which had infallible APIs) to 1.0 (which has the `Result` but in 99.9% of the cases will still be infallible for these actions).
it'd make sense to propagate these errors up to the caller
